### ISSUE TITLE
How to Pass Custom message in Allure Report when "Element not found message occurs" in during automation testing?

### ISSUE THREAD

**Issue by kkashyap1707** [allure-framework/allure-jasmine#18]
Hi Team,

I am using allure reporting for Protractor Jasmine framework. 
![here is my report screenshot](https://cloud.githubusercontent.com/assets/4715140/22825515/b79e6b76-efb3-11e6-8527-f740511da803.png)

I wants to pass custom messages into my test case instead of stack trace messages shown in the above screenshot. 

**Scenario :+1:** 
**Launch the browser
Enter user name in Email field.**  

Here it might be due to some reason the exact element for Email field not found. In this case stack trace information says : 
**Failed: No element found using locator: By(css selector, login-page > div > div.column.left > form > div:nth-child(1) > input)**

I wants to pass a custom message instead of this stack trace information,

Please let me know how to implement it.

Thanks
Keshav

**Comment by crk2904** [comment]
Hi Keshav , 
Always check whether DOM element is present or not before any operation, if it is present -- do operation , otherwise throw error.
You can write your own custom exception class as follows:

```
//BaseError.js
class BaseError extends Error {
    constructor (message) {
    
      // Calling parent constructor of base Error class.
      super(message);
      
      // Saving class name in the property of our custom error as a shortcut.
      this.name = this.constructor.name;

      // Capturing stack trace, excluding constructor call from it.
      Error.captureStackTrace(this, this.constructor);
          
    }
  };

  module.exports = BaseError;
```

Then extend this class to have new customized error messages:

```
//ElementNotPresentError
const BaseError = require('./BaseError');
class ElementNotPresentError extends BaseError {
  constructor (elementName) {
    super('\'' + elementName + '\'is not present  '|| ' Element is not present');
  }
};

module.exports = ElementNotPresentError;
```

and import this module in your test case as : 
```
//spec.js
const ElementNotPresentError = require('../pathToModule//ElementNotPresentError');

describe('Testing Custom Error for No Such Element Error',function(){
    it('This IT will fail',function(){
        browser.get('http://www.way2automation.com/angularjs-protractor/multiform/#/form/profile');
       //element with invalid name
       var invalidElement = element(by.xpath('.//*[@name="Name"]'));

       //as isPresent() method returns promise object , you have to write promise, You can have wrapper methods for the same.

        new Promise(function(resolve,reject){
            invalidElement.isPresent().then(isPresent=>{
                console.log(isPresent)
                if(isPresent==false){
                    reject(new ElementNotPresentError('invalid Element'));
                }
            })
        }).catch(error=>{
            if(error instanceof ElementNotPresentError){
                setTimeout(function() { throw new ElementNotPresentError('invalid Element'); },1);
            }
        })
    })
})

})
```

```
Output :
1) Testing Custom Error for No Such Element Error This IT will fail
  Message:
    ElementNotPresentError: 'invalid Element'is not present
  Stack:
    ElementNotPresentError: 'invalid Element'is not present
        at Timeout._onTimeout (D:\spec.js:15:47)
        at ontimeout (timers.js:475:11)
        at tryOnTimeout (timers.js:310:5)
        at Timer.listOnTimeout (timers.js:270:5)

1 spec, 1 failure
Finished in 1.699 seconds

[18:35:43] I/launcher - 0 instance(s) of WebDriver still running
[18:35:43] I/launcher - chrome #01 failed 1 test(s)
[18:35:43] I/launcher - overall: 1 failed spec(s)
[18:35:43] E/launcher - Process exited with error code 1
```
