### ISSUE TITLE
allure report will generate with exception

### ISSUE THREAD

**Issue by shivanthalakmal** [allure-framework/allure-jasmine#23]
**Note:** report will generate successfully but, end of the execution it throws exception type error log as below, any reason for that ??

[08:24:58] E/launcher - Cannot read property 'currentStep' of undefined
[08:24:58] E/launcher - TypeError: Cannot read property 'currentStep' of undefined
    at Allure.addAttachment (E:\deliverable-projets\cambio-html-taf\node_modules\allure-js-commons\index.js:75:27)
    at Allure.createAttachment (E:\deliverable-projets\cambio-html-taf\node_modules\allure-js-commons\runtime.js:48:29)
    at E:\deliverable-projets\cambio-html-taf\node_modules\allure-js-commons\runtime.js:45:25
    at E:\deliverable-projets\cambio-html-taf\cambio-hybrid-demo\cambio-demo-tests\testplans\suiteConfig.ts:87:30
    at ManagedPromise.invokeCallback_ (E:\deliverable-projets\cambio-html-taf\node_modules\selenium-webdriver\lib\promise.js:1366:14)
    at TaskQueue.execute_ (E:\deliverable-projets\cambio-html-taf\node_modules\selenium-webdriver\lib\promise.js:2970:14)
    at TaskQueue.executeNext_ (E:\deliverable-projets\cambio-html-taf\node_modules\selenium-webdriver\lib\promise.js:2953:27)
    at asyncRun (E:\deliverable-projets\cambio-html-taf\node_modules\selenium-webdriver\lib\promise.js:2813:27)
    at E:\deliverable-projets\cambio-html-taf\node_modules\selenium-webdriver\lib\promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[08:24:58] E/launcher - Process exited with error code 199
npm ERR! Test failed.  See above for more details.

Applied report generate code:

![image](https://cloud.githubusercontent.com/assets/7554175/24436551/be478f82-1459-11e7-9426-bcad41bbc318.png)

**Comment by shivanthalakmal** [comment]
Hi all @just-boris , @baev, @ctapobep,

any update on this issue. ?

**Comment by saisagar-vuddagiri** [comment]
Hi @shivanthalakmal ,

Could you please let me know whether Allure report is generating successfully even when test fails? 

I raised a new issue. Please refer #24

**Comment by bipint** [comment]
var AllureReporter = require('jasmine-allure-reporter');
    jasmine.getEnv().addReporter(new AllureReporter({
      resultsDir: 'allure-results'
    }));


    jasmine.getEnv().afterEach(function(done){
      browser.takeScreenshot().then(function (png) {
        allure.createAttachment('Screenshot', function () {
          return new Buffer(png, 'base64')
        }, 'image/png')();
        done();
      });
  });

**Comment by sravankumarreddybade** [comment]
With above code i am able to resolve the  E/launcher - Cannot read property 'currentStep' of undefined exception but reports are not generating when tests are failed with above code.
